{
 "title": "NodeInfo by Experiments Copy",
 "time": { "from": "2022-11-28T10:52:25.000Z", "to": "2022-11-28T10:57:39.000Z" },
 "templating": {
  "list": [
   {
    "name": "exp",
    "label": "Simulation Title",
    "query": "select hashed as metrics from experiments;"
   },
   {
    "name": "epochvar",
    "label": "Choose the trails",
    "query": "select unique(epochtime) from nodesummary where exp_id=(select id from experiments where hashed = \"${exp}\");"
   }
  ]
 },
 "panels": [
  { "title": "Trail Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "epochvar" },
  {
   "title": "Chances of cacheHit per request",
   "type": "gauge",
   "description": "It is toatlCacheHits/TotalCacheLookups",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select nodename as metric,numberofcachehits/numberofcachelookups as value from nodesummary where epochtime=\"${epochvar}\"\n"
    }
   ]
  },
  {
   "title": "Nodes participated in experiment",
   "type": "table",
   "description": "These are the nodes took part in the epiremnt ",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select nodename,nodetype  from nodesummary where epochtime=\"${epochvar}\""
    }
   ]
  },
  {
   "title": "CacheMiss vs CacheHits",
   "type": "barchart",
   "description": "It is toatlCacheHits/TotalCacheLookups",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select nodename as metric,numberofcachehits/numberofcachelookups as cacheHits,numberofcachemiss/numberofcachelookups as cacheMiss from nodesummary where epochtime=\"${epochvar}\"\n"
    }
   ]
  },
  {
   "title": "Number of requests handled by nodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select nodename as metric, numberofrequestshandled as value  from nodesummary where  epochtime=\"${epochvar}\""
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select total_network_time as TOTAL_NETWORK_USAGE_TIME,total_answer_first_time as TOTAL_MINIMUM_TIME_NEEDED_TO_RESOLVE from exp_summery where epoch=\"${epochvar}\""
    }
   ]
  },
  {
   "title": "Number of QueryMade",
   "type": "stat",
   "description": "Number of QueryMade",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select total_asks as NumberOfQueries from exp_summery where epoch=\"${epochvar}\""
    }
   ]
  },
  {
   "title": "cacheHit vs HDD HIT",
   "type": "barchart",
   "description": "Number of Req Answered vs Forwarded",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select nodename as metric,numberofcachehits as cacheHits,numberofhddhits as hddHits from nodesummary where epochtime=\"${epochvar}\"\n"
    }
   ]
  },
  {
   "title": "Number of Req Answered vs Forwarded",
   "type": "barchart",
   "description": "Number of Req Answered vs Forwarded",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select nodename as metric,numberofrequestsansweredBYME as answeredByNode,numberofrequestsforwarded as forwardedByNode from nodesummary where epochtime=\"${epochvar}\"\n"
    }
   ]
  },
  {
   "title": "Number of packets Transfered",
   "type": "stat",
   "description": "Number of packets used in the trail",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select total_network_usage as NumberOfPacketstransfered from exp_summery where epoch=\"${epochvar}\""
    }
   ]
  },
  {
   "title": "Average HopCountsUsedToGetAnswer",
   "type": "stat",
   "description": "Average HopCountsUsed to solve the query",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ceil(total_minimum_hopcount / total_asks) as AverageMinimumHopsRequiredToResolve from exp_summery where epoch=\"${epochvar}\""
    }
   ]
  },
  {
   "title": "Total Network Usage Time",
   "type": "stat",
   "description": "Total Network Usage Time",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select concat(total_network_time,\"ms\") as NumberOfPacketstransfered from exp_summery where epoch=\"${epochvar}\""
    }
   ]
  },
  { "title": "Simulation Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "exp" },
  {
   "title": "All trails requests and answer summary",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "targets": [
    {
     "rawSql": "select epochtime as time_sec,nodename as metric,numberofrequestshandled,numberofrequestsansweredBYME,numberofrequestsforwarded from nodesummary where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "All trails cache info summary",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Cache Count" } },
   "targets": [
    {
     "rawSql": "select epochtime as time_sec,nodename as metric,numberofcachehits,numberofcachemiss,numberofcachelookups from nodesummary where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "All trails HDD info summary",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "HDD lookup count" } },
   "targets": [
    {
     "rawSql": "select epochtime as time_sec,nodename as metric,numberofhddhits,numberofhddmiss,numberofhddlookups from nodesummary where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "All trails PowerConsumpion  info summary",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "PowerUnits" } },
   "targets": [
    {
     "rawSql": "select epochtime as time_sec,nodename as metric,pc from nodesummary where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  { "title": "Simulation Results ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }, "repeat": "exp" },
  {
   "title": "AVg hop counts req to get reach destination",
   "type": "stat",
   "description": "Number of QueryMade",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ceil(avg(total_minimum_hopcount/total_asks)) as AvgHopCount from exp_summery  where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "Average packets particiapted in expiremnts",
   "type": "stat",
   "description": "Number of QueryMade",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(total_network_usage) as AvgPacketsSent from exp_summery  where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "Average PowerConsumption from all trails",
   "type": "stat",
   "description": "Number of QueryMade",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(pc) from nodesummary where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "Avg time req to reach destiantion",
   "type": "stat",
   "description": "Average Time taken to get Answer",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select concat(sum(total_answer_first_time)/sum(total_asks),\"ms\") as AvgTimeReqtoAnswer from exp_summery  where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "Network usage time info",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "select epoch as time_sec,concat(\"Trail\",CAST(@a:=@a+1 as int)) metric,total_network_time,total_answer_first_time from exp_summery, (SELECT @a:= 0) AS a where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  },
  {
   "title": "Total Average Network Usage",
   "type": "stat",
   "description": "Number of QueryMade",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select concat(avg(total_network_time),\"ms\") as AvgNetworkUsage from exp_summery  where exp_id=(select id from experiments where hashed = \"${exp}\");"
    }
   ]
  }
 ]
}